### ISSUE TITLE
Создать генератор арифметических задач

### ISSUE THREAD

**Issue by ilmpc** [geekycats-school/tglib#3]
По сути нужно написать модуль tasks, сейчас там только заглушка.

**Comment by grumpyLemons** [comment]
У генератора сейчас для линейных коэффициент может быть равен нулю, тогда никакой из ответов не подходит, а еще в квадратичных стоит условие "> 0" для постановки знака +, если будет ноль, то там знака вовсе не будет

**Comment by ghost** [comment]
починил
